services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: review-setter
      POSTGRES_PASSWORD: review-setter
      POSTGRES_DB: review-setter
    restart: always
    networks:
      - lesson
networks:
  lesson:
